"""Runtime client for executing Infoblox WAPI operations.

This is the generic, hand-maintained counterpart to the autogenerated
``tools.py``. Rather than calling one of ~1000 generated functions, the chat
flow produces a structured proposal (operation/method/parameters) and this
client executes it against the Grid with connection pooling, retries, SSL
handling, timeouts and structured (never-raising) error reporting.
"""
import json
import logging
import os
from typing import Any, Dict, List, Optional

import requests
from requests.adapters import HTTPAdapter

try:  # urllib3 ships with requests; import defensively for the Retry helper.
    from urllib3.util.retry import Retry
except Exception:  # pragma: no cover - extremely unlikely
    Retry = None

from backend.config import InfobloxConfig

logger = logging.getLogger(__name__)

_VALID_METHODS = {"GET", "POST", "PUT", "DELETE"}
# PUT/DELETE operate on an existing object reference.
_REF_REQUIRED = {"PUT", "DELETE"}


class WapiClient:
    """Executes validated WAPI calls against an Infoblox Grid Master."""

    def __init__(self, config: InfobloxConfig, session: Optional[requests.Session] = None,
                 supported_objects: Optional[List[str]] = None):
        self.config = config
        self.base_url = f"https://{config.grid_ip}/wapi/{config.wapi_version}/"
        # Use a (connect, read) timeout tuple: cap the connect phase so an
        # unreachable Grid fails fast for interactive callers, while still
        # allowing the configured time for the server to respond.
        connect_timeout = min(config.connection_timeout, 8)
        self.timeout = (connect_timeout, config.connection_timeout)
        self.verify_ssl = config.verify_ssl
        self.session = session or self._build_session(config)
        self.supported_objects = set(
            supported_objects if supported_objects is not None else self._load_supported_objects()
        )

    @staticmethod
    def _build_session(config: InfobloxConfig) -> requests.Session:
        session = requests.Session()
        session.auth = (config.admin_user, config.admin_pass)
        session.verify = config.verify_ssl
        if Retry is not None:
            retry = Retry(
                total=config.max_retries,
                # A connection timeout usually means the Grid is down; don't
                # retry it many times (that turns a 1-shot failure into minutes).
                connect=1,
                backoff_factor=0.5,
                status_forcelist=(500, 502, 503, 504),
                allowed_methods=frozenset(["GET", "POST", "PUT", "DELETE"]),
                raise_on_status=False,
            )
            adapter = HTTPAdapter(max_retries=retry, pool_connections=10, pool_maxsize=10)
            session.mount("https://", adapter)
            session.mount("http://", adapter)
        if not config.verify_ssl:
            # Avoid noisy InsecureRequestWarning spam when SSL verification is off.
            try:
                requests.packages.urllib3.disable_warnings()  # type: ignore[attr-defined]
            except Exception:
                pass
        return session

    @staticmethod
    def _load_supported_objects() -> List[str]:
        for candidate in ("schema.json", "network_schema.json"):
            if os.path.exists(candidate):
                try:
                    with open(candidate, "r") as f:
                        return json.load(f).get("supported_objects", [])
                except (json.JSONDecodeError, OSError) as e:
                    logger.warning("Could not load supported objects from %s: %s", candidate, e)
        return []

    def validate(self, operation: str, method: str, ref: Optional[str] = None) -> Optional[str]:
        """Returns an error string if the call is invalid, else None."""
        if not operation or not isinstance(operation, str):
            return "Missing or invalid 'operation'."
        method = (method or "").upper()
        if method not in _VALID_METHODS:
            return f"Unsupported method '{method}'. Expected one of {sorted(_VALID_METHODS)}."
        if method in _REF_REQUIRED and not ref:
            return f"Method '{method}' requires an object reference ('ref')."
        if self.supported_objects and method in ("GET", "POST") and operation not in self.supported_objects:
            return f"Unknown WAPI object '{operation}'."
        return None

    def execute(self, operation: str, method: str = "GET",
                parameters: Optional[Dict[str, Any]] = None,
                ref: Optional[str] = None) -> Dict[str, Any]:
        """Execute a single WAPI operation. Always returns a structured dict."""
        method = (method or "GET").upper()
        parameters = parameters or {}

        error = self.validate(operation, method, ref)
        if error:
            return {"success": False, "error": error, "status_code": None}

        # PUT/DELETE target the object reference directly; GET/POST target the type.
        target = ref if method in _REF_REQUIRED else operation
        url = f"{self.base_url}{target}"

        try:
            if method == "GET":
                resp = self.session.get(url, params=parameters, timeout=self.timeout)
            elif method == "POST":
                resp = self.session.post(url, json=parameters, timeout=self.timeout)
            elif method == "PUT":
                resp = self.session.put(url, json=parameters, timeout=self.timeout)
            else:  # DELETE
                resp = self.session.delete(url, timeout=self.timeout)

            return self._build_result(resp)
        except requests.exceptions.RequestException as e:
            logger.error("WAPI %s %s failed: %s", method, url, e)
            return {"success": False, "error": str(e), "status_code": None}

    @staticmethod
    def _build_result(resp: requests.Response) -> Dict[str, Any]:
        try:
            data = resp.json() if resp.content else None
        except ValueError:
            data = resp.text or None

        if resp.ok:
            return {"success": True, "status_code": resp.status_code, "data": data}

        # WAPI returns JSON error bodies like {"Error": "...", "text": "..."}.
        message = None
        if isinstance(data, dict):
            message = data.get("text") or data.get("Error")
        return {
            "success": False,
            "status_code": resp.status_code,
            "error": message or f"WAPI returned HTTP {resp.status_code}",
            "data": data,
        }

    @staticmethod
    def _is_placeholder_ref(ref) -> bool:
        """True if `ref` is missing or an LLM placeholder like
        ``<network_ref_from_previous_GET>`` rather than a real WAPI _ref."""
        if not ref or not isinstance(ref, str):
            return True
        r = ref.strip().lower()
        return r.startswith("<") or "previous" in r or "from_" in r or "{" in r

    @staticmethod
    def _ref_from_result(result: Dict[str, Any]):
        """Extracts a usable _ref from a call result (a GET returning exactly one
        object, or a POST/PUT that returned the object reference string)."""
        if not result.get("success"):
            return None
        data = result.get("data")
        if isinstance(data, list) and len(data) == 1 and isinstance(data[0], dict):
            return data[0].get("_ref")
        if isinstance(data, str) and "/" in data:
            return data
        return None

    @staticmethod
    def _ref_object_type(ref: str):
        """The WAPI object type encoded at the start of a _ref (before the first '/')."""
        return ref.split("/", 1)[0] if isinstance(ref, str) and "/" in ref else None

    def execute_batch(self, operations: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Execute operations in order, collecting every result.

        Supports simple ref-chaining: a PUT/DELETE whose ``ref`` is missing or a
        placeholder reuses the _ref produced by the most recent prior call (e.g.
        a GET that located the object to delete). This makes "find X then delete
        it" plans work without the planner knowing the _ref up front.
        """
        results = []
        last_ref = None
        for op in operations:
            if not isinstance(op, dict):
                results.append({"success": False, "error": "Each operation must be an object."})
                continue

            method = (op.get("method") or "GET").upper()
            ref = op.get("ref")
            if method in ("PUT", "DELETE") and self._is_placeholder_ref(ref) and last_ref:
                # Only chain a ref whose object type matches this mutating op, so a
                # GET on one object can't feed a DELETE on an unrelated type.
                if self._ref_object_type(last_ref) == op.get("operation"):
                    ref = last_ref
                else:
                    results.append({
                        "success": False,
                        "error": (f"Refusing to {method} {op.get('operation')}: no matching "
                                  f"object reference was resolved from the previous step."),
                    })
                    continue

            result = self.execute(
                operation=op.get("operation"),
                method=method,
                parameters=op.get("parameters"),
                ref=ref,
            )
            results.append(result)

            resolved = self._ref_from_result(result)
            if resolved:
                last_ref = resolved
        return results

    # Identifying field(s) per object type, used to pre-flight whether a create
    # would duplicate an existing object.
    _IDENTITY_FIELDS = {
        "network": ["network"],
        "networkcontainer": ["network"],
        "ipv6network": ["network"],
        "range": ["start_addr", "end_addr"],
        "fixedaddress": ["ipv4addr"],
        "record:a": ["name"],
        "record:aaaa": ["name"],
        "record:host": ["name"],
        "record:cname": ["name"],
        "record:mx": ["name"],
        "record:ptr": ["ptrdname"],
        "zone_auth": ["fqdn"],
        "network_view": ["name"],
        "view": ["name"],
    }

    # Useful fields to return when showing an existing (duplicate) object.
    _DETAIL_FIELDS = {
        "network": "network,network_view,comment,options",
        "ipv6network": "network,network_view,comment,options",
        "networkcontainer": "network,network_view,comment",
        "range": "start_addr,end_addr,network,comment,disable,options",
        "fixedaddress": "ipv4addr,mac,network,comment",
        "record:a": "name,ipv4addr,view,ttl,comment",
        "record:aaaa": "name,ipv6addr,view,ttl,comment",
        "record:host": "name,ipv4addrs,view,comment",
        "record:cname": "name,canonical,view,comment",
        "record:mx": "name,mail_exchanger,preference,view",
        "record:ptr": "ptrdname,view,comment",
        "zone_auth": "fqdn,view,comment",
        "network_view": "name,comment",
        "view": "name,comment",
    }

    def _find_existing(self, operation: str, parameters: Dict[str, Any]):
        """Returns the full existing object a create would collide with, or None.
        Best-effort; only for object types with a known identity field."""
        key_fields = self._IDENTITY_FIELDS.get(operation)
        if not key_fields:
            return None
        search = {k: parameters.get(k) for k in key_fields if parameters.get(k) is not None}
        if len(search) != len(key_fields):
            return None
        detail = self._DETAIL_FIELDS.get(operation)
        if detail:
            search = {**search, "_return_fields": detail}
        result = self.execute(operation, "GET", search)
        data = result.get("data")
        if result.get("success") and isinstance(data, list) and data:
            return data[0]
        return None

    def preflight(self, operations: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Returns risk warnings for a plan WITHOUT mutating anything.

        Flags destructive deletes and creates that would duplicate an existing
        object (which WAPI would reject). Each warning: {index, level, message}.
        """
        warnings = []
        for i, op in enumerate(operations):
            if not isinstance(op, dict):
                continue
            method = (op.get("method") or "GET").upper()
            operation = op.get("operation")
            params = op.get("parameters") or {}
            if method == "DELETE":
                ref = op.get("ref")
                target = operation if self._is_placeholder_ref(ref) else ref
                warnings.append({"index": i, "level": "danger",
                                 "message": f"DELETE permanently removes the matched {target} object."})
            elif method == "PUT":
                warnings.append({"index": i, "level": "warn",
                                 "message": f"PUT overwrites fields on an existing {operation}."})
            elif method == "POST":
                existing = self._find_existing(operation, params)
                if existing:
                    warnings.append({
                        "index": i,
                        "level": "warn",
                        "message": f"a {operation} matching this already exists; "
                                   "creating it would fail as a duplicate.",
                        "details": existing,
                    })
        return warnings
